# Generated by Django 3.1.4 on 2020-12-22 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalTaskModel',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('system', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_planner_app.externaltaskmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalTaskEffortLeftModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(choices=[('SYSTEM_ANALYSIS', 'System Analysis'), ('DEVELOPMENT', 'Development'), ('SYSTEM_TESTING', 'System Testing')], max_length=255)),
                ('hours', models.FloatField()),
                ('external_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_planner_app.externaltaskmodel')),
            ],
        ),
    ]
