# Generated by Django 3.1.4 on 2020-12-22 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_planner_app', '0003_auto_20201222_0951'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExternalTaskModel',
            new_name='ExternalTaskDbRecord',
        ),
        migrations.RenameModel(
            old_name='ExternalTaskEffortLeftModel',
            new_name='ExternalTaskEffortLeftDbRecord',
        ),
    ]
