# Generated by Django 3.1.4 on 2020-12-23 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_planner_app', '0004_auto_20201222_1251'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExternalTaskDbRecord',
            new_name='ExternalTaskDAO',
        ),
        migrations.RenameModel(
            old_name='ExternalTaskEffortLeftDbRecord',
            new_name='ExternalTaskEffortLeftDAO',
        ),
        migrations.RenameField(
            model_name='externaltaskeffortleftdao',
            old_name='activity',
            new_name='ability',
        ),
    ]
