version: '3.8'

services:

  delivery-planner-server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    entrypoint: ['/usr/src/app/entrypoint.sh']
    ports:
      - 8000:8000
    depends_on:
      - delivery-planner-database
    env_file:
      - ./server/.env.prod

  delivery-planner-database:
    container_name: delivery-planner-database
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=delivery-planner
      - POSTGRES_PASSWORD=delivery-planner
      - POSTGRES_DB=delivery-planner-dev
    expose:
      - 5432

  delivery-planner-client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
      args:
        - NODE_ENV=production
        - REACT_APP_DELIVERY_PLANNER_APP_URL=${REACT_APP_DELIVERY_PLANNER_APP_URL}
    ports:
      - 3000:80
    depends_on:
      - delivery-planner-server
