version: '3.8'

services:

  delivery-planner-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: delivery-planner-server
    depends_on:
      - delivery-planner-database
    environment:
      - DEBUG=1
      - SECRET_KEY=super-secret-dev-key
      - DJANGO_ALLOWED_HOSTS=*
      - CORS_ORIGIN_WHITELIST=http://localhost:3000 http://127.0.0.1:3000
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=delivery-planner-dev
      - SQL_USER=delivery-planner
      - SQL_PASSWORD=delivery-planner
      - SQL_HOST=delivery-planner-database
      - SQL_PORT=5432
    ports:
      - 8000:8000
    volumes:
      - ./server:/usr/src/app

  delivery-planner-database:
    container_name: delivery-planner-database
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=delivery-planner
      - POSTGRES_PASSWORD=delivery-planner
      - POSTGRES_DB=delivery-planner-dev
    expose:
      - 5432
    volumes:
      - delivery-planner-database:/var/lib/postgresql/data

  delivery-planner-client:
    build:
      context: ./client
    command: npm start
    container_name: delivery-planner-client
    depends_on:
      - delivery-planner-server
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./client:/usr/src/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
      - REACT_APP_DELIVERY_PLANNER_APP_URL=http://localhost:8000/delivery_planner_app

volumes:
  delivery-planner-database:
