version: '3.8'

services:

  delivery-planner-server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    ports:
      - 8000:8000
    depends_on:
      - delivery-planner-database
    env_file:
      - ./server/.env.prod

  delivery-planner-database:
    container_name: delivery-planner-database
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=delivery-planner
      - POSTGRES_PASSWORD=delivery-planner
      - POSTGRES_DB=delivery-planner-dev
    expose:
      - 5432

  delivery-planner-client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
    depends_on:
      - delivery-planner-server
